# first install RUST in MAC 1 curl — proto ‘=https’ — tlsv1.2 -sSf https://sh.rustup.rs | sh

name: pytorch
channels:
        - conda-forge
        - huggingface
        - pytorch
dependencies:
        - python=3.8
        - jupyter
        - pip
        - pip:
                - accelerate==0.10.0
                - evaluate==0.1.2
                - datasets==2.3.2
                - multipledispatch==0.6.0
                - numba==0.55.2
                - numpy==1.22.4
                - pandas==1.4.3
                - scikit-learn==1.1.1
                - scipy==1.8.1
                - -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ submodlib
                - torchvision==0.11.2
                - torch==1.10.0
                - tqdm==4.64.0
                - transformers==4.20.1